[profile.default]
src = "src"
test = "test"
out = "out"
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20000
bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 512
